"""add google_oauth_token table

Revision ID: 01064e6fc6d6
Revises: 4a5b6c7d8e9f
Create Date: 2026-01-16 22:55:24.461399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01064e6fc6d6'
down_revision: Union[str, None] = '4a5b6c7d8e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_oauth_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_oauth_token_id'), 'google_oauth_token', ['id'], unique=False)
    op.drop_constraint('memory_item_embedding_memory_item_id_key', 'memory_item_embedding', type_='unique')
    op.drop_constraint('uq_person_display_name', 'person', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_person_display_name', 'person', ['display_name'])
    op.create_unique_constraint('memory_item_embedding_memory_item_id_key', 'memory_item_embedding', ['memory_item_id'])
    op.drop_index(op.f('ix_google_oauth_token_id'), table_name='google_oauth_token')
    op.drop_table('google_oauth_token')
    # ### end Alembic commands ###
