"""add google_oauth_token table

Revision ID: 01064e6fc6d6
Revises: 52ec1cb1b1eb
Create Date: 2026-01-16 22:55:24.461399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01064e6fc6d6'
down_revision: Union[str, None] = '52ec1cb1b1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_oauth_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_oauth_token_id'), 'google_oauth_token', ['id'], unique=False)
    # Drop constraint only if table exists
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'memory_item_embedding') THEN
                ALTER TABLE memory_item_embedding DROP CONSTRAINT IF EXISTS memory_item_embedding_memory_item_id_key;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'person') THEN
                ALTER TABLE person DROP CONSTRAINT IF EXISTS uq_person_display_name;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate constraints only if tables exist
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'memory_item_embedding') THEN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memory_item_embedding_memory_item_id_key') THEN
                    ALTER TABLE memory_item_embedding ADD CONSTRAINT memory_item_embedding_memory_item_id_key UNIQUE (memory_item_id);
                END IF;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'person') THEN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_person_display_name') THEN
                    ALTER TABLE person ADD CONSTRAINT uq_person_display_name UNIQUE (display_name);
                END IF;
            END IF;
        END $$;
    """)
    op.drop_index(op.f('ix_google_oauth_token_id'), table_name='google_oauth_token')
    op.drop_table('google_oauth_token')
    # ### end Alembic commands ###
