"""init tables

Revision ID: 52ec1cb1b1eb
Revises: 
Create Date: 2026-01-16 19:44:57.618691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52ec1cb1b1eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_display_name'), 'person', ['display_name'], unique=False)
    op.create_index(op.f('ix_person_id'), 'person', ['id'], unique=False)
    op.create_table('calendar_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_event_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('attendees_raw', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('related_person_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_event_id'), 'calendar_event', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_event_provider'), 'calendar_event', ['provider'], unique=False)
    op.create_index(op.f('ix_calendar_event_provider_event_id'), 'calendar_event', ['provider_event_id'], unique=True)
    op.create_index(op.f('ix_calendar_event_related_person_id'), 'calendar_event', ['related_person_id'], unique=False)
    op.create_index(op.f('ix_calendar_event_start_time'), 'calendar_event', ['start_time'], unique=False)
    op.create_table('memory_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('IDEA', 'REMINDER', 'NOTE', name='memoryitemtype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('normalized_summary', sa.Text(), nullable=True),
    sa.Column('related_person_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DISCUSSED', 'ARCHIVED', name='memoryitemstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_item_due_at'), 'memory_item', ['due_at'], unique=False)
    op.create_index(op.f('ix_memory_item_id'), 'memory_item', ['id'], unique=False)
    op.create_index(op.f('ix_memory_item_related_person_id'), 'memory_item', ['related_person_id'], unique=False)
    op.create_index(op.f('ix_memory_item_status'), 'memory_item', ['status'], unique=False)
    op.create_index(op.f('ix_memory_item_type'), 'memory_item', ['type'], unique=False)
    op.create_table('interaction_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_item_id', sa.UUID(), nullable=False),
    sa.Column('calendar_event_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATED', 'REMINDED', 'DISCUSSED', 'POSTPONED', 'MERGED', name='interactionlogaction'), nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_event.id'], ),
    sa.ForeignKeyConstraint(['memory_item_id'], ['memory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_log_action'), 'interaction_log', ['action'], unique=False)
    op.create_index(op.f('ix_interaction_log_calendar_event_id'), 'interaction_log', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_interaction_log_created_at'), 'interaction_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_interaction_log_id'), 'interaction_log', ['id'], unique=False)
    op.create_index(op.f('ix_interaction_log_memory_item_id'), 'interaction_log', ['memory_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_log_memory_item_id'), table_name='interaction_log')
    op.drop_index(op.f('ix_interaction_log_id'), table_name='interaction_log')
    op.drop_index(op.f('ix_interaction_log_created_at'), table_name='interaction_log')
    op.drop_index(op.f('ix_interaction_log_calendar_event_id'), table_name='interaction_log')
    op.drop_index(op.f('ix_interaction_log_action'), table_name='interaction_log')
    op.drop_table('interaction_log')
    op.drop_index(op.f('ix_memory_item_type'), table_name='memory_item')
    op.drop_index(op.f('ix_memory_item_status'), table_name='memory_item')
    op.drop_index(op.f('ix_memory_item_related_person_id'), table_name='memory_item')
    op.drop_index(op.f('ix_memory_item_id'), table_name='memory_item')
    op.drop_index(op.f('ix_memory_item_due_at'), table_name='memory_item')
    op.drop_table('memory_item')
    op.drop_index(op.f('ix_calendar_event_start_time'), table_name='calendar_event')
    op.drop_index(op.f('ix_calendar_event_related_person_id'), table_name='calendar_event')
    op.drop_index(op.f('ix_calendar_event_provider_event_id'), table_name='calendar_event')
    op.drop_index(op.f('ix_calendar_event_provider'), table_name='calendar_event')
    op.drop_index(op.f('ix_calendar_event_id'), table_name='calendar_event')
    op.drop_table('calendar_event')
    op.drop_index(op.f('ix_person_id'), table_name='person')
    op.drop_index(op.f('ix_person_display_name'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
