"""add notification_outbox table

Revision ID: b60631410199
Revises: 01064e6fc6d6
Create Date: 2026-01-16 23:35:28.677843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60631410199'
down_revision: Union[str, None] = '01064e6fc6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'PUSH', 'TEST', name='notificationchannel'), nullable=False),
    sa.Column('calendar_event_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('briefing_text', sa.Text(), nullable=False),
    sa.Column('push_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_event.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_event_id', 'channel', 'scheduled_for', name='uq_notification_event_channel_scheduled')
    )
    op.create_index(op.f('ix_notification_outbox_calendar_event_id'), 'notification_outbox', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_channel'), 'notification_outbox', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_outbox_created_at'), 'notification_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_id'), 'notification_outbox', ['id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_person_id'), 'notification_outbox', ['person_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_scheduled_for'), 'notification_outbox', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'), 'notification_outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_outbox_status'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_scheduled_for'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_person_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_created_at'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_channel'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_calendar_event_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    # ### end Alembic commands ###
